"""
AI-Generated Content Detector.

Detects whether text was likely generated by an AI language model (ChatGPT,
Claude, Grok, etc.) using multiple structural and statistical signals:

  1. Fictional / unverifiable entity detection
  2. Sentence length uniformity analysis
  3. Transition phrase density
  4. Passive voice density
  5. Formulaic adverb density
  6. Paragraph structure regularity
  7. Hedging uniformity (balanced "some say X, others Y" patterns)
  8. Web corroboration for key entities (institutions, journals, people)

None of these signals alone is conclusive, but combined they produce a
reliable indicator of AI authorship.
"""

import re
import math
import statistics
try:
    from ddgs import DDGS
except ImportError:
    DDGS = None
from app.services.text_utils import normalize_text, normalize_for_heuristics

# ---------------------------------------------------------------------------
# Signal 1: Explicit AI / Fictional markers in the text itself
# ---------------------------------------------------------------------------
EXPLICIT_AI_MARKERS = [
    'as an ai language model', 'generated by gpt', 'generated by ai',
    'i cannot fulfill', 'as a large language model',
    'this is a fictional', 'fabricated news',
    'in this hypothetical scenario', 'for testing purposes',
    'generated by chatgpt', 'generated by claude', 'generated by grok',
    'written by ai', 'ai-generated', 'created by an ai',
    'as a machine learning model', 'as an artificial intelligence',
    'since i am an ai', 'i am a text-based ai', 'as an automated assistant',
    'not a real person', 'fabricated text', 'simulated scenario',
]

# The word "fictional" appearing near an entity name (e.g. "the fictional
# International Vision Research Institute") is a dead giveaway.
FICTIONAL_QUALIFIER_PATTERN = re.compile(
    r'\b(?:fictional|fictitious|hypothetical|imaginary|made[- ]?up|synthetic|not\s+real|simulated|fabricated|fake)\b',
    re.IGNORECASE,
)

# ---------------------------------------------------------------------------
# Signal 2: Transition / connector phrases that AI overuses
# ---------------------------------------------------------------------------
AI_TRANSITION_PHRASES = [
    'furthermore', 'moreover', 'in addition', 'additionally',
    'consequently', 'as a result', 'in conclusion', 'to summarize',
    'it is worth noting', 'it should be noted', 'notably',
    'on the other hand', 'in contrast', 'conversely',
    'nevertheless', 'nonetheless', 'notwithstanding',
    'in light of', 'with regard to', 'in terms of',
    'it is important to note', 'it is essential to',
    'this highlights', 'this underscores', 'this suggests',
    'moving forward', 'going forward', 'looking ahead',
    'that being said', 'having said that', 'with that in mind',
    'broadly speaking', 'generally speaking',
    'in the broader context', 'from a broader perspective',
]

# ---------------------------------------------------------------------------
# Signal 3: Formulaic hedging phrases AI uses for "balance"
# ---------------------------------------------------------------------------
AI_HEDGING_PAIRS = [
    # (one side, other side) — AI loves to present both sides formulaically
    (r'(?:some|several|many)\s+(?:\w+\s+){0,3}(?:argue|claim|believe|say|suggest|contend)',
     r'(?:others|while others|but others|some others)\s+(?:\w+\s+){0,3}(?:argue|claim|believe|say|suggest|contend|disagree|counter)'),
    (r'(?:proponents|supporters|advocates)\s+(?:of|say|argue|claim|believe)',
     r'(?:critics|opponents|skeptics|detractors)\s+(?:say|argue|claim|believe|counter|warn)'),
    (r'(?:on\s+(?:the\s+)?one\s+hand)',
     r'(?:on\s+the\s+other\s+hand)'),
]

# ---------------------------------------------------------------------------
# Signal 4: Passive voice patterns
# ---------------------------------------------------------------------------
PASSIVE_VOICE_PATTERN = re.compile(
    r'\b(?:is|are|was|were|been|being|be)\s+'
    r'(?:reportedly|said\s+to\s+be|expected\s+to\s+be|believed\s+to\s+be|'
    r'thought\s+to\s+be|considered\s+to\s+be|'
    r'(?:\w+(?:ed|en))\b)',
    re.IGNORECASE,
)

# Specific "reported speech" patterns AI loves
REPORTED_SPEECH_PATTERNS = [
    r'(?:is|are)\s+said\s+to\b',
    r'(?:is|are)\s+expected\s+to\b',
    r'(?:is|are)\s+believed\s+to\b',
    r'(?:is|are)\s+reported\s+to\b',
    r'(?:has|have)\s+reportedly\b',
    r'(?:is|are)\s+reportedly\b',
    r'\breportedly\b',
    r'\ballegedly\b',
    r'\bpurportedly\b',
]
_compiled_reported = [re.compile(p, re.IGNORECASE) for p in REPORTED_SPEECH_PATTERNS]

# ---------------------------------------------------------------------------
# Signal 5: Formulaic adverbs AI overuses
# ---------------------------------------------------------------------------
AI_ADVERBS = [
    'significantly', 'potentially', 'particularly', 'specifically',
    'essentially', 'fundamentally', 'ultimately', 'increasingly',
    'subsequently', 'accordingly', 'presumably', 'reportedly',
    'apparently', 'evidently', 'purportedly', 'ostensibly',
    'arguably', 'undoubtedly', 'inevitably', 'inherently',
    'predominantly', 'substantially', 'considerably', 'remarkably',
]

# ---------------------------------------------------------------------------
# Signal 6: Entity extraction for web corroboration
# ---------------------------------------------------------------------------

# Patterns to extract institution / organization names
INSTITUTION_PATTERN = re.compile(
    r'(?:the\s+)?'
    r'(?:fictional\s+)?'
    r'('
    r'(?:[A-Z][a-zA-Z]+\s+){1,5}'  # 1-5 capitalized words
    r'(?:Institute|University|Foundation|Center|Centre|Laboratory|Lab|'
    r'Organization|Organisation|Society|Association|Agency|Authority|'
    r'Commission|Council|Board|Bureau|Department|Ministry|'
    r'Corporation|Company|Group|Consortium|Alliance|Coalition|Network|'
    r'Hospital|Clinic|Academy|School|College)'
    r')'
    r'(?:\s+\([A-Z]{2,6}\))?',  # optional acronym like (IVRI)
    re.MULTILINE,
)

# Extract journal / publication names (hardened against arbitrary whitespace)
JOURNAL_PATTERN = re.compile(
    r'(?:the\s+)?'
    r'(?:fictional\s+|fake\s+|imaginary\s+)?'
    r'(?:Journal|Bulletin|Review|Proceedings|Annals|Archives|Gazette|'
    r'Quarterly|Monthly|Weekly|Daily|Tribune|Herald|Times|Post|Chronicle)'
    r'[\s\W]+of[\s\W]+'
    r'(?:[A-Z][a-zA-Z]+\s*){1,5}',
    re.MULTILINE,
)

# Extract study/report references
STUDY_PATTERN = re.compile(
    r'(?:a\s+)?(?:new\s+|recent\s+|latest\s+|major\s+|landmark\s+)?'
    r'(?:study|report|analysis|survey|investigation|paper|research)'
    r'(?:\s+(?:released|published|conducted|carried\s+out|led\s+by|from|by))'
    r'(?:\s+(?:today|recently|this\s+(?:week|month|year)))?'
    r'(?:\s+by\s+(?:researchers|scientists|experts|analysts|doctors)\s+'
    r'(?:at|from)\s+(?:the\s+)?)?'
    r'(.{0,100})',
    re.IGNORECASE,
)

# Acronym pattern — extract things like (IVRI), (WHO), etc.
ACRONYM_PATTERN = re.compile(r'\(([A-Z]{2,8})\)')


def _extract_key_entities(text):
    """
    Extract institutions, journals, and acronyms that should be verifiable.
    Returns a list of entity strings to search for.
    """
    entities = []

    # Institutions
    for m in INSTITUTION_PATTERN.finditer(text):
        name = m.group(1).strip()
        if len(name) > 10:  # Filter out very short matches
            entities.append(name)

    # Journals
    for m in JOURNAL_PATTERN.finditer(text):
        name = m.group(0).strip()
        if 'fictional' not in name.lower():
            entities.append(name)
        else:
            # The text literally says "fictional" — dead giveaway
            entities.append(name.replace('fictional ', '').replace('Fictional ', ''))

    # Acronyms — only if they're not common known ones
    COMMON_ACRONYMS = {
        'US', 'UK', 'EU', 'UN', 'WHO', 'NASA', 'FBI', 'CIA', 'BBC', 'CNN',
        'GDP', 'CEO', 'CTO', 'CFO', 'COO', 'PhD', 'MD', 'AP', 'AFP',
        'IMF', 'NATO', 'UNICEF', 'UNESCO', 'ISRO', 'MIT', 'IIT',
        'AIIMS', 'NIH', 'CDC', 'FDA', 'EPA', 'DOJ', 'DOD', 'NSA',
        'FIDE', 'ICC', 'FIFA', 'IOC', 'NBA', 'NFL', 'MLB', 'NHL',
        'IPL', 'BCCI', 'ECB', 'RBI', 'SEBI', 'SEC', 'FTC',
    }
    for m in ACRONYM_PATTERN.finditer(text):
        acr = m.group(1)
        if acr not in COMMON_ACRONYMS:
            entities.append(acr)

    return entities


def _verify_entity_exists(entity):
    """
    Search the web for an entity. Returns True if it appears to be real
    (i.e., has meaningful search results), False if it seems fictional.
    """
    if DDGS is None:
        return True  # Can't verify, assume real to avoid false positives
    try:
        with DDGS() as ddgs:
            results = list(ddgs.text(f'"{entity}"', max_results=3))

        if not results:
            return False

        # Check if any result actually mentions this entity
        entity_lower = entity.lower()
        entity_words = set(entity_lower.split())

        for r in results:
            combined = (r.get('title', '') + ' ' + r.get('body', '')).lower()
            # Check if the entity name or most of its words appear
            matched_words = sum(1 for w in entity_words if w in combined)
            if matched_words >= len(entity_words) * 0.6:
                return True

        return False

    except Exception:
        # On error, assume the entity is real to avoid false positives
        return True


# ---------------------------------------------------------------------------
# Signal analysis functions
# ---------------------------------------------------------------------------

def _check_explicit_markers(text_lower):
    """Check for explicit AI / fictional content markers."""
    markers_found = []
    for marker in EXPLICIT_AI_MARKERS:
        if marker in text_lower:
            markers_found.append(marker)

    # Check for "fictional" qualifier near entity names
    if FICTIONAL_QUALIFIER_PATTERN.search(text_lower):
        markers_found.append('fictional/fictitious qualifier used')

    return markers_found


def _analyze_sentence_uniformity(text):
    """
    AI text tends to have very uniform sentence lengths.
    Human text has much more variation.

    Returns a score from 0.0 (high variation = human) to 1.0 (uniform = AI).
    """
    # Split into sentences
    sentences = re.split(r'[.!?]+', text)
    sentences = [s.strip() for s in sentences if len(s.strip()) > 10]

    if len(sentences) < 4:
        return 0.0  # Not enough data

    lengths = [len(s.split()) for s in sentences]
    mean_len = statistics.mean(lengths)
    if mean_len < 5:
        return 0.0

    stdev = statistics.stdev(lengths)
    cv = stdev / mean_len  # Coefficient of variation

    # AI typically has CV < 0.35, humans > 0.50
    if cv < 0.25:
        return 0.85
    elif cv < 0.35:
        return 0.60
    elif cv < 0.45:
        return 0.30
    else:
        return 0.0


def _analyze_transition_density(text_lower):
    """
    Count AI-typical transition phrases per sentence.
    AI text has a much higher density than human writing.

    Returns (score, count).
    """
    sentences = re.split(r'[.!?]+', text_lower)
    sentences = [s.strip() for s in sentences if len(s.strip()) > 10]
    num_sentences = max(len(sentences), 1)

    count = 0
    for phrase in AI_TRANSITION_PHRASES:
        count += text_lower.count(phrase)

    density = count / num_sentences

    if density > 0.5:
        return 0.80, count
    elif density > 0.3:
        return 0.50, count
    elif density > 0.2:
        return 0.25, count
    else:
        return 0.0, count


def _analyze_hedging_balance(text):
    """
    AI loves to present both sides of an argument in a formulaic way.
    E.g., "Some experts argue X... while others contend Y."

    Returns a score from 0.0 to 1.0.
    """
    pair_count = 0
    for pattern_a, pattern_b in AI_HEDGING_PAIRS:
        has_a = re.search(pattern_a, text, re.IGNORECASE)
        has_b = re.search(pattern_b, text, re.IGNORECASE)
        if has_a and has_b:
            pair_count += 1

    if pair_count >= 2:
        return 0.75
    elif pair_count == 1:
        return 0.35
    return 0.0


def _analyze_passive_voice(text):
    """
    AI-generated news tends to use more passive voice and reported speech
    than human journalists.

    Returns (score, count).
    """
    sentences = re.split(r'[.!?]+', text)
    sentences = [s.strip() for s in sentences if len(s.strip()) > 10]
    num_sentences = max(len(sentences), 1)

    passive_count = len(PASSIVE_VOICE_PATTERN.findall(text))
    reported_count = sum(len(p.findall(text)) for p in _compiled_reported)

    total = passive_count + reported_count
    density = total / num_sentences

    if density > 0.8:
        return 0.70, total
    elif density > 0.5:
        return 0.45, total
    elif density > 0.3:
        return 0.20, total
    else:
        return 0.0, total


def _analyze_adverb_density(text_lower):
    """
    AI overuses specific adverbs like "significantly", "potentially", etc.

    Returns (score, count).
    """
    words = text_lower.split()
    total_words = max(len(words), 1)

    count = 0
    for adverb in AI_ADVERBS:
        count += text_lower.count(adverb)

    density = count / total_words

    if density > 0.02:
        return 0.65, count
    elif density > 0.01:
        return 0.35, count
    elif density > 0.005:
        return 0.15, count
    else:
        return 0.0, count


def _analyze_paragraph_regularity(text):
    """
    AI paragraphs tend to be similar in length and follow a consistent
    structure (topic sentence → elaboration → conclusion).

    Returns a score from 0.0 to 1.0.
    """
    paragraphs = [p.strip() for p in text.split('\n') if len(p.strip()) > 20]

    if len(paragraphs) < 3:
        return 0.0

    lengths = [len(p.split()) for p in paragraphs]
    mean_len = statistics.mean(lengths)
    if mean_len < 10:
        return 0.0

    stdev = statistics.stdev(lengths)
    cv = stdev / mean_len

    if cv < 0.20:
        return 0.70
    elif cv < 0.35:
        return 0.40
    elif cv < 0.50:
        return 0.15
    else:
        return 0.0


def _verify_entities_exist(text):
    """
    Extract key entities from the text and verify they exist on the web.
    Fictional entities are a very strong AI-generation signal.

    Returns (fictional_entities, verified_entities).
    """
    entities = _extract_key_entities(text)
    fictional = []
    verified = []

    for entity in entities[:5]:  # Limit to 5 to control latency
        if _verify_entity_exists(entity):
            verified.append(entity)
        else:
            fictional.append(entity)

    return fictional, verified


# ---------------------------------------------------------------------------
# Main detection function
# ---------------------------------------------------------------------------

def detect_ai_content(text, verify_entities=True):
    """
    Analyze text for signs of AI generation.

    Args:
        text: The text to analyze.
        verify_entities: If True, search the web to verify whether
            institutions/journals/people mentioned in the text actually
            exist. This adds ~2-5 seconds but is very powerful.

    Returns:
        dict: {
            'is_ai_generated': bool,
            'ai_probability': float (0.0 - 1.0),
            'signals': list of (signal_name, score, description),
            'fictional_entities': list of entity names that couldn't be found,
            'verified_entities': list of entity names that were found,
        }
    """
    # Robustly normalize text before any heuristic checks
    text = normalize_text(text)
    if not text or len(text) < 80:
        return {
            'is_ai_generated': False,
            'ai_probability': 0.0,
            'signals': [],
            'fictional_entities': [],
            'verified_entities': [],
        }

    text_lower = normalize_for_heuristics(text)
    signals = []
    weighted_scores = []

    # --- Signal 1: Explicit markers (weight: very high) ---
    explicit_markers = _check_explicit_markers(text_lower)
    if explicit_markers:
        score = min(len(explicit_markers) * 0.5, 1.0)
        signals.append(('explicit_ai_markers', score,
                        f'Contains explicit AI/fictional markers: {", ".join(explicit_markers)}'))
        weighted_scores.append(('explicit_ai_markers', score, 3.0))  # weight 3.0

    # --- Signal 2: Sentence length uniformity (weight: medium) ---
    uniformity_score = _analyze_sentence_uniformity(text)
    if uniformity_score > 0.0:
        signals.append(('sentence_uniformity', uniformity_score,
                        f'Sentence lengths are unusually uniform (AI-typical pattern)'))
        weighted_scores.append(('sentence_uniformity', uniformity_score, 1.0))

    # --- Signal 3: Transition phrase density (weight: medium) ---
    transition_score, transition_count = _analyze_transition_density(text_lower)
    if transition_score > 0.0:
        signals.append(('transition_density', transition_score,
                        f'High density of AI-typical transition phrases ({transition_count} found)'))
        weighted_scores.append(('transition_density', transition_score, 1.2))

    # --- Signal 4: Hedging balance (weight: medium-high) ---
    hedging_score = _analyze_hedging_balance(text)
    if hedging_score > 0.0:
        signals.append(('hedging_balance', hedging_score,
                        f'Formulaic balanced hedging pattern detected (AI signature)'))
        weighted_scores.append(('hedging_balance', hedging_score, 1.5))

    # --- Signal 5: Passive voice / reported speech (weight: low-medium) ---
    passive_score, passive_count = _analyze_passive_voice(text)
    if passive_score > 0.0:
        signals.append(('passive_voice', passive_score,
                        f'High passive voice / reported speech density ({passive_count} instances)'))
        weighted_scores.append(('passive_voice', passive_score, 0.8))

    # --- Signal 6: Adverb density (weight: low) ---
    adverb_score, adverb_count = _analyze_adverb_density(text_lower)
    if adverb_score > 0.0:
        signals.append(('adverb_density', adverb_score,
                        f'Elevated AI-typical adverb usage ({adverb_count} instances)'))
        weighted_scores.append(('adverb_density', adverb_score, 0.7))

    # --- Signal 7: Paragraph regularity (weight: low-medium) ---
    para_score = _analyze_paragraph_regularity(text)
    if para_score > 0.0:
        signals.append(('paragraph_regularity', para_score,
                        f'Paragraph lengths are unusually regular (AI-typical)'))
        weighted_scores.append(('paragraph_regularity', para_score, 0.8))

    # --- Signal 8: Fictional entity verification (weight: VERY high) ---
    fictional_entities = []
    verified_entities = []

    if verify_entities:
        fictional_entities, verified_entities = _verify_entities_exist(text)
        if fictional_entities:
            entity_score = min(len(fictional_entities) * 0.5, 1.0)
            signals.append(('fictional_entities', entity_score,
                            f'Unverifiable entities found: {", ".join(fictional_entities)}'))
            weighted_scores.append(('fictional_entities', entity_score, 4.0))  # highest weight

    # Also check if "fictional" is literally used as a qualifier
    fictional_qualifier_matches = FICTIONAL_QUALIFIER_PATTERN.findall(text)
    if fictional_qualifier_matches:
        signals.append(('fictional_qualifier', 1.0,
                        f'Text explicitly uses fictional qualifiers: {", ".join(fictional_qualifier_matches)}'))
        weighted_scores.append(('fictional_qualifier', 1.0, 5.0))  # automatic detection

    # --- Combine scores ---
    if not weighted_scores:
        ai_probability = 0.0
    else:
        total_weight = sum(w for _, _, w in weighted_scores)
        weighted_sum = sum(score * weight for _, score, weight in weighted_scores)
        ai_probability = weighted_sum / total_weight

        # Boost if multiple signals agree (convergent evidence)
        active_signals = sum(1 for _, s, _ in weighted_scores if s > 0.3)
        if active_signals >= 4:
            ai_probability = min(ai_probability * 1.3, 1.0)
        elif active_signals >= 3:
            ai_probability = min(ai_probability * 1.15, 1.0)

    # Clamp
    ai_probability = max(0.0, min(ai_probability, 0.99))

    # Threshold for binary decision
    is_ai_generated = ai_probability >= 0.40

    return {
        'is_ai_generated': is_ai_generated,
        'ai_probability': round(ai_probability, 4),
        'signals': [(name, round(score, 3), desc) for name, score, desc in signals],
        'fictional_entities': fictional_entities,
        'verified_entities': verified_entities,
    }
