"""
ML classifier service.
Wraps the trained TF-IDF + Logistic Regression model for inference,
with a robust heuristic fallback when no model is available.
"""

import os
import re
from app.services.text_utils import normalize_text, normalize_for_heuristics

# Global model cache
_model = None
_vectorizer = None
_model_type = None


def _get_model_paths():
    """Get model file paths from config or defaults."""
    base_dir = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..'))
    model_dir = os.path.join(base_dir, 'saved_models')
    return {
        'pipeline': os.path.join(model_dir, 'tfidf_logreg_pipeline.joblib'),
        'vectorizer': os.path.join(model_dir, 'tfidf_vectorizer.joblib'),
        'model': os.path.join(model_dir, 'logreg_model.joblib'),
    }


def load_model():
    """Load the trained model into memory. Returns True if successful."""
    global _model, _vectorizer, _model_type

    if _model is not None:
        return True

    paths = _get_model_paths()

    try:
        # Try loading the full pipeline first
        if os.path.exists(paths['pipeline']):
            _model = joblib.load(paths['pipeline'])
            _model_type = 'pipeline'
            print(f"[Classifier] Loaded pipeline model from {paths['pipeline']}")
            return True

        # Try loading vectorizer + model separately
        if os.path.exists(paths['vectorizer']) and os.path.exists(paths['model']):
            _vectorizer = joblib.load(paths['vectorizer'])
            _model = joblib.load(paths['model'])
            _model_type = 'separate'
            print("[Classifier] Loaded separate vectorizer + model")
            return True

    except Exception as e:
        print(f"[Classifier] Error loading model: {e}")

    print("[Classifier] No trained model found. Using heuristic classifier.")
    _model_type = 'heuristic'
    return False


# ---------------------------------------------------------------------------
# Signal dictionaries for the heuristic classifier
# ---------------------------------------------------------------------------

SENSATIONALIST_WORDS = [
    'shocking', 'bombshell', 'exposed', 'breaking', "you won't believe",
    'unbelievable', 'urgent', 'terrifying', 'alarming', 'explosive',
    'scandal', 'outrageous', 'insane', 'mind-blowing',
]

CONSPIRACY_LANGUAGE = [
    'deep state', 'false flag', 'cover-up', 'coverup', 'shadow government',
    'cabal', 'globalist', 'new world order', 'illuminati', 'puppet masters',
    'controlled opposition', 'psyop', 'plandemic',
]

CLICKBAIT_PHRASES = [
    "doctors don't want you to know", "share before deleted",
    "wake up sheeple", "they don't want you to know",
    "share before they delete", "one weird trick",
    "what they're hiding", "this changes everything",
    "mainstream media won't tell you", "banned from the internet",
    "share before it's too late",
]

HEALTH_MISINFO = [
    'big pharma', 'miracle cure', 'vaccine causes autism', 'vaccines cause autism',
    'vaccine cause autism', 'doctors hate',
    'natural remedy they', 'essential oils cure', 'government poison',
    'vaccines are poison', 'detox your body', 'suppressed cure',
]

POLITICAL_EXTREMISM = [
    'stolen election', 'deep state coup', 'communist agenda',
    'marxist takeover', 'great replacement', 'white genocide',
    'radical left agenda', 'radical right agenda',
]

AI_GENERATED_PHRASES = [
    'as an ai language model', 'generated by gpt', 'generated by ai',
    'fabricated news for testing only', 'this is a fictional',
    'i cannot fulfill this request', 'as a large language model',
    'it is important to note that', 'it is worth noting that',
    'in conclusion,', 'ultimately,', 'in summary,',
    'generated by chatgpt', 'generated by claude', 'generated by grok',
    'written by ai', 'ai-generated', 'created by an ai',
    'as a machine learning model', 'as an artificial intelligence',
    'since i am an ai', 'i am a text-based ai', 'as an automated assistant',
    'not a real person', 'fabricated text', 'simulated scenario',
]

FICTIONAL_QUALIFIERS = [
    'the fictional', 'is a fictional', 'hypothetical scenario',
    'fictitious', 'imaginary', 'made up', 'made-up',
    'synthetic', 'not real', 'simulated', 'fabricated', 'fake'
]

UNRELIABLE_SOURCES_PHRASES = [
    'viral social media', 'social media posts', 'whatsapp forward',
    'facebook post', 'tiktok video', 'twitter thread', 'reddit thread',
]

SKETCHY_DOMAINS = [
    'infowars', 'naturalnews', 'beforeitsnews', 'thegatewaypundit',
    'worldtruth.tv', 'yournewswire', 'newspunch', 'globalresearch.ca',
]

TROLL_PHRASES = [
    'gangbanged by', 'without any hunger issues', 'drank bleach',
    'injected lysol', 'ate tide pods'
]

# Extraordinary / impossible claim patterns (regex)
EXTRAORDINARY_CLAIM_PATTERNS = [
    # Absurd financial claims
    r'(?:bitcoin|btc|ethereum|eth)\s+(?:reached|hit|surpass|worth)\s+\$?\d[\d,]*\s*(?:million|billion|trillion)',
    r'(?:stock|share)\s+(?:price|value)\s+(?:crashed?|fell|dropped?)\s+to\s+\$?0',
    r'(?:national\s+debt|deficit)\s+(?:was\s+)?(?:paid\s+off|eliminated|wiped|erased)',
    r'giving\s+away\s+\$?\d[\d,]*\s*(?:million|billion|trillion)?\s*(?:to\s+every|to\s+each|to\s+all)',
    r'\$\d[\d,]*\s*(?:million|billion)\s+(?:to\s+every|to\s+each|per\s+person)',
    r'gdp\s+(?:grew|growth|increased|surged|jumped)\s+(?:by\s+)?\d{2,}\s*%',
    # Absurd political claims
    r'(?:resigned|stepping\s+down|abdicated)\s+as\s+(?:president|prime\s+minister|king|queen|emperor)',
    r'declared\s+war\s+on\s+(?:canada|mexico|uk|united\s+kingdom|france|germany|japan|australia)',
    r'(?:alien|ufo|extraterrestrial)s?\s+(?:landed|arrived|confirmed|discovered)',
    r'secretly\s+deployed\s+(?:by|to|for|in)',
    r'(?:cia|fbi|mi6|mossad|government)\s+(?:secretly|covertly)\s+(?:controls?|deployed|using)',
    # Death hoaxes and celebrity misinformation
    r'(?:has\s+)?(?:died|passed\s+away|been\s+killed|been\s+assassinated).*(?:confirmed|breaking)',
    r'(?:arrested|jailed|imprisoned)\s+for\s+(?:treason|crimes\s+against\s+humanity)',
    # Impossible science/health claims
    r'(?:cure|cures)\s+(?:for\s+)?(?:cancer|hiv|aids|diabetes|alzheimer)',
    r'(?:vaccine|vaccines)\s+(?:cause|causes|causing)\s+(?:autism|death|infertility)',
]

_compiled_extraordinary = [re.compile(p, re.IGNORECASE) for p in EXTRAORDINARY_CLAIM_PATTERNS]

# Viral hoax template phrases
VIRAL_HOAX_PHRASES = [
    'giving away', 'free money', 'free cash',
    'to every citizen', 'to every user', 'to every person',
    'to every american', 'to every indian', 'to all citizens',
    'has been secretly', 'was secretly', 'covertly',
    'sending shockwaves', 'stunned the world', 'stunned the nation',
    'in a stunning move', 'in a shocking move', 'in a bombshell',
    'world leaders are panicking', 'governments are scrambling',
    'the internet is breaking', 'the internet has gone wild',
    'completely eliminated', 'totally eradicated',
    'in 190 countries', 'across all countries',
    'anonymous sources confirm', 'sources close to',
    'whistleblower reveals', 'leaked documents show',
]

ATTRIBUTION_PHRASES = [
    'according to', 'reuters', 'associated press', ' ap ', 'bbc',
    ' said', 'confirmed', 'spokesperson', 'press release',
    'in a statement', 'told reporters', 'official said',
    'department said', 'ministry said', 'reported by',
]

HEDGING_LANGUAGE = [
    'allegedly', 'reportedly', 'appears to', 'is believed to',
    'sources say', 'it is unclear', 'unconfirmed', 'may have',
    'could be', 'is expected to', 'remains to be seen',
]


def _heuristic_predict(text):
    """
    Robust heuristic-based prediction when no ML model is available.
    Scores multiple FAKE and REAL signal categories against the text.

    Returns the standard predict() contract:
        {
            "label": "FAKE" or "REAL",
            "confidence": float 0-1,
            "fake_prob": float 0-1,
            "real_prob": float 0-1,
            "mode": "heuristic",
            "features": list of triggered signal descriptions
        }
    """
    if not text or not isinstance(text, str):
        return {
            'label': 'REAL',
            'confidence': 0.5,
            'fake_prob': 0.5,
            'real_prob': 0.5,
            'mode': 'heuristic',
            'features': [],
            # Legacy keys for DB compatibility
            'top_features': [],
            'model_used': 'heuristic',
        }

    # Apply robust text normalization
    text = normalize_text(text)
    text_lower = normalize_for_heuristics(text)
    
    fake_score = 0.0
    features = []
    
    # --- FAKE signals ---

    # 1. Sensationalist words
    for word in SENSATIONALIST_WORDS:
        if word in text_lower:
            fake_score += 0.06
            features.append(f"sensationalist: \"{word}\"")

    # 2. Conspiracy language
    for phrase in CONSPIRACY_LANGUAGE:
        if phrase in text_lower:
            fake_score += 0.08
            features.append(f"conspiracy: \"{phrase}\"")

    # 3. Clickbait phrases
    for phrase in CLICKBAIT_PHRASES:
        if phrase in text_lower:
            fake_score += 0.10
            features.append(f"clickbait: \"{phrase}\"")

    # 4. Health misinformation
    for phrase in HEALTH_MISINFO:
        if phrase in text_lower:
            fake_score += 0.08
            features.append(f"health misinfo: \"{phrase}\"")

    # 5. Political extremism
    for phrase in POLITICAL_EXTREMISM:
        if phrase in text_lower:
            fake_score += 0.07
            features.append(f"extremism: \"{phrase}\"")

    # 6. AI generated phrases
    for phrase in AI_GENERATED_PHRASES:
        if phrase in text_lower:
            fake_score += 0.30  # moderate score for common AI phrases (not conclusive on their own unless very explicit)
            if 'language model' in phrase or 'generated by' in phrase or 'cannot fulfill' in phrase:
                fake_score += 0.69  # explicit markers get higher score (total 0.99)
            features.append(f"ai generated / formulaic: \"{phrase}\"")

    # 6b. Fictional qualifiers
    for phrase in FICTIONAL_QUALIFIERS:
        if phrase in text_lower:
            fake_score += 0.99
            features.append(f"fictional qualifier: \"{phrase}\"")

    # 7. Unreliable sources mentioned
    for phrase in UNRELIABLE_SOURCES_PHRASES:
        if phrase in text_lower:
            fake_score += 0.80
            features.append(f"unreliable source: \"{phrase}\"")

    # 8. Sketchy domains mentioned in text
    for domain in SKETCHY_DOMAINS:
        if domain in text_lower:
            fake_score += 0.08
            features.append(f"sketchy source: \"{domain}\"")

    # 9. Joke / Troll Phrases
    for phrase in TROLL_PHRASES:
        if phrase in text_lower:
            fake_score += 0.99  # very high score for obvious troll/joke claims
            features.append(f"obvious troll/joke claim: \"{phrase}\"")

    # 10. Extraordinary / impossible claims
    extraordinary_matches = [p.pattern for p in _compiled_extraordinary if p.search(text)]
    if extraordinary_matches:
        fake_score += 0.50
        features.append(f"extraordinary/impossible claim detected ({len(extraordinary_matches)} patterns)")

    # 11. Viral hoax template phrases
    hoax_count = 0
    for phrase in VIRAL_HOAX_PHRASES:
        if phrase in text_lower:
            hoax_count += 1
    if hoax_count >= 1:
        bump = min(hoax_count * 0.12, 0.50)
        fake_score += bump
        features.append(f"viral hoax patterns ({hoax_count} phrases)")

    # 12. Excessive ALL CAPS (use ORIGINAL text, not lowered)
    words = text.split()
    total_words = len(words) if words else 1
    caps_words = sum(1 for w in words if w.isupper() and len(w) > 2)
    caps_ratio = caps_words / total_words
    if caps_ratio > 0.05:
        bump = min(caps_ratio * 2.0, 0.20)
        fake_score += bump
        features.append(f"excessive ALL CAPS ({caps_words}/{total_words} words)")

    # 13. Punctuation abuse (use ORIGINAL text)
    excl_runs = len(re.findall(r'!{2,}', text))
    quest_runs = len(re.findall(r'\?{2,}', text))
    if excl_runs > 0:
        fake_score += min(excl_runs * 0.04, 0.15)
        features.append(f"punctuation abuse: {excl_runs} exclamation clusters")
    if quest_runs > 0:
        fake_score += min(quest_runs * 0.03, 0.10)
        features.append(f"punctuation abuse: {quest_runs} question clusters")

    # 14. Missing attribution (no source references in text)
    has_attribution = any(p in text_lower for p in ATTRIBUTION_PHRASES)
    if not has_attribution and total_words > 30:
        fake_score += 0.08
        features.append("no attribution or source references found")

    # --- REAL signals (reduce fake_score) ---
    # NOTE: Real signal reductions are CAPPED and will NOT override strong
    # fake signals (extraordinary claims, AI markers, etc.)

    # 1. Attribution phrases present
    attribution_count = sum(1 for p in ATTRIBUTION_PHRASES if p in text_lower)
    if attribution_count > 0:
        # Don't let attribution reduce score if extraordinary claim detected
        if not extraordinary_matches:
            reduction = min(attribution_count * 0.04, 0.15)
            fake_score -= reduction
            features.append(f"attribution found ({attribution_count} phrases)")

    # 2. Hedging language
    hedging_count = sum(1 for p in HEDGING_LANGUAGE if p in text_lower)
    if hedging_count > 0:
        reduction = min(hedging_count * 0.03, 0.10)
        fake_score -= reduction
        features.append(f"hedging language ({hedging_count} phrases)")

    # 3. Precise numbers, percentages, dates
    # NOTE: Precise data should NOT reduce fake score when the claim itself
    # is extraordinary — fabricated claims often include precise-looking numbers
    numbers = re.findall(r'\b\d+\.?\d*\s*%', text)  # percentages
    dates = re.findall(
        r'\b(?:January|February|March|April|May|June|July|August|September|'
        r'October|November|December)\s+\d{1,2}(?:,?\s*\d{4})?'
        r'|\b\d{1,2}/\d{1,2}/\d{2,4}\b'
        r'|\b\d{4}-\d{2}-\d{2}\b',
        text, re.IGNORECASE
    )
    precise_count = len(numbers) + len(dates)
    if precise_count >= 2 and not extraordinary_matches:
        reduction = min(precise_count * 0.03, 0.12)
        fake_score -= reduction
        features.append(f"precise data ({len(numbers)} percentages, {len(dates)} dates)")

    # Clamp score to [0.02, 0.98]
    fake_score = max(0.02, min(fake_score, 0.98))

    # Determine label using threshold
    label = 'FAKE' if fake_score >= 0.35 else 'REAL'
    confidence = fake_score if label == 'FAKE' else (1.0 - fake_score)

    return {
        'label': label,
        'confidence': round(confidence, 4),
        'fake_prob': round(fake_score, 4),
        'real_prob': round(1.0 - fake_score, 4),
        'mode': 'heuristic',
        'features': features,
        # Legacy keys the DB / API layer already reference
        'top_features': features,
        'model_used': 'heuristic',
    }


def predict(text):
    """
    Main prediction pipeline.
    Combines ML classification with strong heuristic overrides.
    """
    global _model, _vectorizer, _model_type

    if _model_type is None:
        load_model()

    # Apply robust text normalization
    normalized_text = normalize_text(text)

    # Check for immediate heuristic overrides FIRST
    if _model_type == 'heuristic' or _model is None:
        return _heuristic_predict(normalized_text)

    from app.services.preprocessor import preprocess_pipeline

    try:
        if _model_type == 'pipeline':
            processed_text = preprocess_pipeline(normalized_text)
            proba = _model.predict_proba([processed_text])[0]
            prediction = _model.predict([processed_text])[0]
            top_features = _extract_top_features_pipeline(processed_text)

        elif _model_type == 'separate':
            processed_text = preprocess_pipeline(normalized_text)
            tfidf_vector = _vectorizer.transform([processed_text])
            proba = _model.predict_proba(tfidf_vector)[0]
            prediction = _model.predict(tfidf_vector)[0]
            top_features = _extract_top_features_separate(tfidf_vector)

        else:
            return _heuristic_predict(normalized_text)

        # Map prediction to label (class 1 = FAKE, class 0 = REAL)
        label = 'FAKE' if prediction == 1 else 'REAL'
        fake_prob = float(proba[1]) if len(proba) > 1 else (float(proba[0]) if prediction == 1 else 1.0 - float(proba[0]))
        real_prob = 1.0 - fake_prob
        confidence = float(max(proba))

        return {
            'label': label,
            'confidence': round(confidence, 4),
            'fake_prob': round(fake_prob, 4),
            'real_prob': round(real_prob, 4),
            'mode': 'tfidf',
            'features': top_features,
            'top_features': top_features,
            'model_used': 'tfidf_logreg',
        }

    except Exception as e:
        print(f"[Classifier] Prediction error: {e}")
        return _heuristic_predict(text)


def _extract_top_features_pipeline(text, n=10):
    """Extract top contributing features from a sklearn Pipeline."""
    try:
        vectorizer = _model.named_steps.get('tfidf') or _model.named_steps.get('vectorizer')
        classifier = _model.named_steps.get('classifier') or _model.named_steps.get('model')

        if vectorizer is None or classifier is None:
            return []

        feature_names = vectorizer.get_feature_names_out()
        tfidf_vector = vectorizer.transform([text])
        coefficients = classifier.coef_[0]

        nonzero_indices = tfidf_vector.nonzero()[1]
        feature_scores = [
            (feature_names[i], float(coefficients[i] * tfidf_vector[0, i]))
            for i in nonzero_indices
        ]
        feature_scores.sort(key=lambda x: abs(x[1]), reverse=True)
        return [f[0] for f in feature_scores[:n]]

    except Exception:
        return []


def _extract_top_features_separate(tfidf_vector, n=10):
    """Extract top contributing features from separate vectorizer + model."""
    try:
        feature_names = _vectorizer.get_feature_names_out()
        coefficients = _model.coef_[0]

        nonzero_indices = tfidf_vector.nonzero()[1]
        feature_scores = [
            (feature_names[i], float(coefficients[i] * tfidf_vector[0, i]))
            for i in nonzero_indices
        ]
        feature_scores.sort(key=lambda x: abs(x[1]), reverse=True)
        return [f[0] for f in feature_scores[:n]]

    except Exception:
        return []


def get_model_info():
    """Return information about the currently loaded model."""
    return {
        'model_type': _model_type or 'not_loaded',
        'is_loaded': _model is not None,
        'paths': _get_model_paths()
    }
