import re
from ddgs import DDGS

# Fact checking domains or trusted sources
TRUSTED_DOMAINS = [
    'snopes.com', 'politifact.com', 'factcheck.org', 'reuters.com',
    'apnews.com', 'bbc.com', 'altnews.in', 'boomlive.in', 'pib.gov.in',
    'newschecker.in', 'vishvasnews.com', 'factly.in', 'afp.com',
    'leadstories.com', 'logically.ai', 'fullfact.org', 'msn.com',
    # General knowledge, news and entertainment domains
    'wikipedia.org', 'imdb.com', 'forbes.com', 'nytimes.com', 'cnn.com',
    'theguardian.com', 'wsj.com', 'washingtonpost.com', 'bloomberg.com',
    'ndtv.com', 'timesofindia.indiatimes.com', 'hindustantimes.com',
    'indianexpress.com', 'thehindu.com', 'news18.com', 'indiatoday.in',
    'yahoo.com', 'variety.com', 'hollywoodreporter.com', 'deadline.com',
    'rollingstone.com', 'billboard.com', 'people.com', 'etonline.com',
    'britannica.com', 'biography.com',
    # Indian regional, entertainment, and digital news domains
    'pinkvilla.com', 'bollywoodhungama.com', 'koimoi.com', 'tellychakkar.com',
    'abplive.com', 'aajtak.in', 'zeenews.india.com', 'dnaindia.com',
    'firstpost.com', 'deccanchronicle.com', 'thestatesman.com',
    'telegraphindia.com', 'mid-day.com', 'tribuneindia.com', 'thequint.com',
    'scroll.in', 'thewire.in', 'livemint.com', 'indiatvnews.com',
    'republicworld.com', 'asianetnews.com', 'mathrubhumi.com',
    'manoramaonline.com', 'dinamalar.com', 'vikatan.com', 'eenadu.net',
    'sakshi.com', 'prajavani.net', 'vijaykarnataka.com', 'assamtribune.com',
    'gujaratsamachar.com', 'sandesh.com', 'lokmat.com'
]

# Keywords that indicate a claim is false
DEBUNK_KEYWORDS = [
    'false', 'debunked', 'misleading', 'fake', 'hoax', 'altered',
    'deepfake', 'digitally altered', 'untrue', 'did not say',
    'never said', 'falsely claiming', 'no evidence', 'unsubstantiated',
    'fabricated', 'baseless', 'unfounded', 'disinformation',
    'misinformation', 'denied', 'refuted', 'not true',
    'no such announcement', 'satire', 'parody',
]

# Keywords that indicate the source is REFUTING / DENYING the claim
REFUTATION_KEYWORDS = [
    'denied', 'denies', 'no evidence', 'not true', 'false claim',
    'did not happen', 'never happened', 'no such', 'unverified',
    'cannot confirm', 'no confirmation', 'rumor', 'rumour',
    'fact check', 'fact-check', 'claim is false', 'rated false',
    'pants on fire', 'mostly false', 'four pinocchios',
]

# Phrases that signal GPT-generated or AI-fabricated content
AI_CONTENT_MARKERS = [
    'as an ai language model', 'generated by gpt', 'generated by ai',
    'i cannot fulfill', 'as a large language model',
    'this is a fictional', 'fabricated news',
    'in this hypothetical scenario', 'for testing purposes',
]

# Extraordinary / impossible claim patterns that should NEVER be auto-verified
# These detect claims that are so outlandish they need extraordinary evidence
EXTRAORDINARY_CLAIM_PATTERNS = [
    # Absurd financial claims
    r'(?:bitcoin|btc|ethereum|eth)\s+(?:reached|hit|surpass|worth)\s+\$?\d[\d,]*\s*(?:million|billion|trillion)',
    r'(?:stock|share)\s+(?:price|value)\s+(?:crashed?|fell|dropped?)\s+to\s+\$?0',
    r'(?:national\s+debt|deficit)\s+(?:was\s+)?(?:paid\s+off|eliminated|wiped|erased)',
    r'giving\s+away\s+\$?\d[\d,]*\s*(?:million|billion|trillion)?\s*(?:to\s+every|to\s+each|to\s+all)',
    r'\$\d[\d,]*\s*(?:million|billion)\s+(?:to\s+every|to\s+each|per\s+person)',
    r'gdp\s+(?:grew|growth|increased|surged|jumped)\s+(?:by\s+)?\d{2,}\s*%',

    # Absurd political claims
    r'(?:resigned|stepping\s+down|abdicated)\s+as\s+(?:president|prime\s+minister|king|queen|emperor)',
    r'declared\s+war\s+on\s+(?:canada|mexico|uk|united\s+kingdom|france|germany|japan|australia)',
    r'(?:alien|ufo|extraterrestrial)s?\s+(?:landed|arrived|confirmed|discovered)',
    r'secretly\s+deployed\s+(?:by|to|for|in)',
    r'(?:cia|fbi|mi6|mossad|government)\s+(?:secretly|covertly)\s+(?:controls?|deployed|using)',

    # Death hoaxes and celebrity misinformation
    r'(?:has\s+)?(?:died|passed\s+away|been\s+killed|been\s+assassinated).*(?:confirmed|breaking)',
    r'(?:arrested|jailed|imprisoned)\s+for\s+(?:treason|crimes\s+against\s+humanity)',

    # Impossible science/health claims
    r'(?:cure|cures)\s+(?:for\s+)?(?:cancer|hiv|aids|diabetes|alzheimer)',
    r'(?:vaccine|vaccines)\s+(?:cause|causes|causing)\s+(?:autism|death|infertility)',
]

# Compiled patterns for efficiency
_compiled_extraordinary = [re.compile(p, re.IGNORECASE) for p in EXTRAORDINARY_CLAIM_PATTERNS]

# Words/phrases that indicate the claim is likely a fantasy or fabrication
FANTASY_INDICATORS = [
    'secretly', 'covertly', 'in a stunning move', 'in a shocking move',
    'sources close to', 'anonymous sources confirm',
    'the government doesn\'t want you to know',
    'banned from the internet', 'censored by',
    'whistleblower reveals', 'leaked documents show',
    'every citizen', 'to every user', 'to all users',
    'in 190 countries', 'across all countries',
    'completely eliminated', 'totally eradicated',
    'sending shockwaves', 'stunned the world',
]


def _contains_ai_markers(text_lower):
    """Check if text contains AI-generated content markers."""
    return any(marker in text_lower for marker in AI_CONTENT_MARKERS)


def _is_extraordinary_claim(text):
    """Check if the claim matches known extraordinary/impossible patterns."""
    return any(p.search(text) for p in _compiled_extraordinary)


def _count_fantasy_indicators(text_lower):
    """Count how many fantasy/fabrication indicator phrases are present."""
    return sum(1 for phrase in FANTASY_INDICATORS if phrase in text_lower)


def _source_confirms_claim(snippet, query_words):
    """
    Check if a source actually CONFIRMS the claim vs just mentioning related topics.
    A source confirms only if it:
    1. Has high keyword overlap (>= 50%)
    2. Does NOT contain refutation keywords
    """
    snippet_lower = snippet.lower() if snippet else ''

    # Check for refutation in this source
    has_refutation = any(kw in snippet_lower for kw in REFUTATION_KEYWORDS)
    if has_refutation:
        return False

    # Check keyword overlap
    if not query_words:
        return False
    matched = sum(1 for w in query_words if w in snippet_lower)
    overlap = matched / len(query_words)

    return overlap >= 0.3


def search_and_verify(text):
    """
    Search the web for the claim and return a fact-check analysis.
    Uses duckduckgo-search (ddgs).

    IMPORTANT: This function is deliberately conservative about marking
    claims as "verified". It is much safer to return "unverified" than
    to falsely verify a fabricated claim.
    """
    # Extract a short query from the text (first sentence or up to 120 chars)
    clean_text = re.sub(r'breaking:?|viral social media|whatsapp forward', '', text, flags=re.IGNORECASE).strip()
    query = clean_text[:120].strip()

    if not query:
        return {'status': 'error', 'message': 'Query too short'}

    text_lower = text.lower()

    # --- Pre-flight checks: block verification for obviously problematic content ---

    # 1. AI-generated content should never be verified
    if _contains_ai_markers(text_lower):
        return {
            'status': 'debunked',
            'message': 'Content contains AI-generated text markers.',
            'sources': []
        }

    # 2. Extraordinary claims need extraordinary evidence — flag them early
    is_extraordinary = _is_extraordinary_claim(text)
    fantasy_count = _count_fantasy_indicators(text_lower)

    try:
        with DDGS() as ddgs:
            results = list(ddgs.text(f"{query} fact check", max_results=5))

        if not results:
            return {'status': 'unverified', 'message': 'No relevant fact-check results found.'}

        debunk_score = 0
        confirm_score = 0
        total_results = len(results)
        sources_used = []
        refutation_found = False

        # Extract meaningful words from query for relevance checking
        query_words = set(re.findall(r'\b[a-zA-Z]{4,}\b', query.lower()))

        for r in results:
            title = r.get('title', '').lower()
            snippet = r.get('body', '').lower()
            url = r.get('href', '')

            combined_text = title + " " + snippet + " " + url
            sources_used.append({'title': r.get('title'), 'url': url, 'snippet': snippet})

            # If a trusted fact checking site explicitly calls it false
            is_trusted = any(domain in url for domain in TRUSTED_DOMAINS)

            has_debunk = any(keyword in combined_text for keyword in DEBUNK_KEYWORDS)
            has_refutation = any(keyword in combined_text for keyword in REFUTATION_KEYWORDS)

            if has_debunk:
                if is_trusted:
                    debunk_score += 2  # Trusted sources carry more weight
                else:
                    debunk_score += 1

            if has_refutation:
                refutation_found = True
                debunk_score += 1

            # Check for numerical contradictions (e.g. claim says '6' but sources say '11')
            claim_numbers = set(re.findall(r'\b\d+\b', query))
            if claim_numbers:
                result_numbers = set(re.findall(r'\b\d+\b', combined_text))
                # Ignore common years to prevent false positives
                result_numbers = {n for n in result_numbers if len(n) < 4}
                claim_numbers_filtered = {n for n in claim_numbers if len(n) < 4}
                if claim_numbers_filtered and result_numbers and not claim_numbers_filtered.intersection(result_numbers):
                    debunk_score += 1  # Contradicting numerical facts

            # Check if this source actually confirms the claim
            if is_trusted and _source_confirms_claim(snippet, query_words):
                confirm_score += 1

        # --- Decision logic ---

        # DEBUNKED: Strong debunk evidence
        if debunk_score >= 2:
            return {
                'status': 'debunked',
                'message': 'Live Web Search: Claim has been debunked by fact-checkers.',
                'sources': sources_used[:3]
            }

        # NEVER verify extraordinary claims unless overwhelmingly confirmed
        if is_extraordinary or fantasy_count >= 2:
            # Even if we found some matching results, extraordinary claims
            # need extraordinary evidence. Require 3+ confirming trusted sources
            # with zero refutation.
            if confirm_score >= 3 and not refutation_found and debunk_score == 0:
                return {
                    'status': 'verified',
                    'message': 'Live Web Search: Extraordinary claim confirmed by multiple credible sources.',
                    'sources': sources_used[:3]
                }
            # Otherwise, stay unverified for extraordinary claims
            return {
                'status': 'unverified',
                'message': 'Live Web Search: Claim is extraordinary and could not be conclusively verified.',
                'sources': sources_used[:3]
            }

        # VERIFIED: Only for normal claims with strong evidence
        # Requirements (much stricter than before):
        # 1. Zero debunk signals
        # 2. At least 2 trusted sources that actually confirm (not just mention)
        # 3. No refutation found anywhere
        # 4. At least 1 total result (changed to be more lenient for general facts)
        if debunk_score == 0 and not refutation_found and total_results >= 1:
            if confirm_score >= 1:
                return {
                    'status': 'verified',
                    'message': 'Live Web Search: Claim is supported by credible sources.',
                    'sources': sources_used[:3]
                }

        return {
            'status': 'unverified',
            'message': 'Live Web Search: Results found, but inconclusive.',
            'sources': sources_used[:3]
        }

    except Exception as e:
        print(f"Web Search Error: {e}")
        return {'status': 'error', 'message': f'Search failed: {str(e)}'}
