import re
try:
    from ddgs import DDGS
except ImportError:
    DDGS = None
from app.services.text_utils import normalize_text, normalize_for_heuristics

# Fact checking domains or trusted sources
TRUSTED_DOMAINS = [
    'snopes.com', 'politifact.com', 'factcheck.org', 'reuters.com',
    'apnews.com', 'bbc.com', 'altnews.in', 'boomlive.in', 'pib.gov.in',
    'newschecker.in', 'vishvasnews.com', 'factly.in', 'afp.com',
    'leadstories.com', 'logically.ai', 'fullfact.org', 'msn.com',
    # General knowledge, news and entertainment domains
    'wikipedia.org', 'imdb.com', 'forbes.com', 'nytimes.com', 'cnn.com',
    'theguardian.com', 'wsj.com', 'washingtonpost.com', 'bloomberg.com',
    'ndtv.com', 'timesofindia.indiatimes.com', 'hindustantimes.com',
    'indianexpress.com', 'thehindu.com', 'news18.com', 'indiatoday.in',
    'yahoo.com', 'variety.com', 'hollywoodreporter.com', 'deadline.com',
    'rollingstone.com', 'billboard.com', 'people.com', 'etonline.com',
    'britannica.com', 'biography.com',
    # Indian regional, entertainment, and digital news domains
    'pinkvilla.com', 'bollywoodhungama.com', 'koimoi.com', 'tellychakkar.com',
    'abplive.com', 'aajtak.in', 'zeenews.india.com', 'dnaindia.com',
    'firstpost.com', 'deccanchronicle.com', 'thestatesman.com',
    'telegraphindia.com', 'mid-day.com', 'tribuneindia.com', 'thequint.com',
    'scroll.in', 'thewire.in', 'livemint.com', 'indiatvnews.com',
    'republicworld.com', 'asianetnews.com', 'mathrubhumi.com',
    'manoramaonline.com', 'dinamalar.com', 'vikatan.com', 'eenadu.net',
    'sakshi.com', 'prajavani.net', 'vijaykarnataka.com', 'assamtribune.com',
    'gujaratsamachar.com', 'sandesh.com', 'lokmat.com',
    # Sports, knowledge, and reference domains
    'espn.com', 'espncricinfo.com', 'sports.yahoo.com', 'bbc.com/sport',
    'chess.com', 'fide.com', 'olympics.com', 'worldathletics.org',
    'cricbuzz.com', 'goal.com', 'transfermarkt.com',
    'chess24.com', 'lichess.org', 'chessbase.com',
    'en.wikipedia.org', 'wikidata.org', 'britannica.com',
]

# Keywords that indicate a claim is false
DEBUNK_KEYWORDS = [
    'false', 'debunked', 'misleading', 'fake', 'hoax', 'altered',
    'deepfake', 'digitally altered', 'untrue', 'did not say',
    'never said', 'falsely claiming', 'no evidence', 'unsubstantiated',
    'fabricated', 'baseless', 'unfounded', 'disinformation',
    'misinformation', 'denied', 'refuted', 'not true',
    'no such announcement', 'satire', 'parody',
]

# Keywords that indicate the source is REFUTING / DENYING the claim
REFUTATION_KEYWORDS = [
    'denied', 'denies', 'no evidence', 'not true', 'false claim',
    'did not happen', 'never happened', 'no such', 'unverified',
    'cannot confirm', 'no confirmation', 'rumor', 'rumour',
    'fact check', 'fact-check', 'claim is false', 'rated false',
    'pants on fire', 'mostly false', 'four pinocchios',
]

# Phrases that signal GPT-generated or AI-fabricated content
AI_CONTENT_MARKERS = [
    'as an ai language model', 'generated by gpt', 'generated by ai',
    'i cannot fulfill', 'as a large language model',
    'this is a fictional', 'fabricated news',
    'in this hypothetical scenario', 'for testing purposes',
    'generated by chatgpt', 'generated by claude', 'generated by grok',
    'written by ai', 'ai-generated', 'created by an ai',
    'as a machine learning model', 'as an artificial intelligence',
    'since i am an ai', 'i am a text-based ai', 'as an automated assistant',
    'not a real person', 'fabricated text', 'simulated scenario',
]

# Extraordinary / impossible claim patterns that should NEVER be auto-verified
# These detect claims that are so outlandish they need extraordinary evidence
EXTRAORDINARY_CLAIM_PATTERNS = [
    # Absurd financial claims
    r'(?:bitcoin|btc|ethereum|eth)\s+(?:reached|hit|surpass|worth)\s+\$?\d[\d,]*\s*(?:million|billion|trillion)',
    r'(?:stock|share)\s+(?:price|value)\s+(?:crashed?|fell|dropped?)\s+to\s+\$?0',
    r'(?:national\s+debt|deficit)\s+(?:was\s+)?(?:paid\s+off|eliminated|wiped|erased)',
    r'giving\s+away\s+\$?\d[\d,]*\s*(?:million|billion|trillion)?\s*(?:to\s+every|to\s+each|to\s+all)',
    r'\$\d[\d,]*\s*(?:million|billion)\s+(?:to\s+every|to\s+each|per\s+person)',
    r'gdp\s+(?:grew|growth|increased|surged|jumped)\s+(?:by\s+)?\d{2,}\s*%',

    # Absurd political claims
    r'(?:resigned|stepping\s+down|abdicated)\s+as\s+(?:president|prime\s+minister|king|queen|emperor)',
    r'declared\s+war\s+on\s+(?:canada|mexico|uk|united\s+kingdom|france|germany|japan|australia)',
    r'(?:alien|ufo|extraterrestrial)s?\s+(?:landed|arrived|confirmed|discovered)',
    r'secretly\s+deployed\s+(?:by|to|for|in)',
    r'(?:cia|fbi|mi6|mossad|government)\s+(?:secretly|covertly)\s+(?:controls?|deployed|using)',

    # Death hoaxes and celebrity misinformation
    r'(?:has\s+)?(?:died|passed\s+away|been\s+killed|been\s+assassinated).*(?:confirmed|breaking)',
    r'(?:arrested|jailed|imprisoned)\s+for\s+(?:treason|crimes\s+against\s+humanity)',

    # Impossible science/health claims
    r'(?:cure|cures)\s+(?:for\s+)?(?:cancer|hiv|aids|diabetes|alzheimer)',
    r'(?:vaccine|vaccines)\s+(?:cause|causes|causing)\s+(?:autism|death|infertility)',
]

# Compiled patterns for efficiency
_compiled_extraordinary = [re.compile(p, re.IGNORECASE) for p in EXTRAORDINARY_CLAIM_PATTERNS]

# Words/phrases that indicate the claim is likely a fantasy or fabrication
FANTASY_INDICATORS = [
    'secretly', 'covertly', 'in a stunning move', 'in a shocking move',
    'sources close to', 'anonymous sources confirm',
    'the government doesn\'t want you to know',
    'banned from the internet', 'censored by',
    'whistleblower reveals', 'leaked documents show',
    'every citizen', 'to every user', 'to all users',
    'in 190 countries', 'across all countries',
    'completely eliminated', 'totally eradicated',
    'sending shockwaves', 'stunned the world',
]

# ---------------------------------------------------------------------------
# Claim type detection — differentiate between simple facts, news/study
# claims, and opinions
# ---------------------------------------------------------------------------

# Patterns indicating a news/study/report claim (needs institution verification)
NEWS_STUDY_CLAIM_PATTERNS = [
    r'(?:a\s+)?(?:new\s+|recent\s+|latest\s+|major\s+)?(?:study|report|analysis|survey|investigation|paper|research)\s+(?:released|published|conducted|carried\s+out|found|shows?|reveals?|suggests?|claims?)',
    r'researchers?\s+(?:at|from|of)\s+(?:the\s+)?',
    r'scientists?\s+(?:at|from|of)\s+(?:the\s+)?',
    r'(?:the\s+)?(?:full\s+)?(?:study|report|paper)\s+(?:is\s+)?(?:expected\s+to\s+be\s+)?(?:published|released)',
    r'(?:journal|bulletin|review|proceedings)\s+of\s+',
    r'data\s+from\s+over\s+\d[\d,]*\s+participants?',
    r'analyzed\s+data\s+from\s+',
]
_compiled_news_study = [re.compile(p, re.IGNORECASE) for p in NEWS_STUDY_CLAIM_PATTERNS]

# Patterns indicating a simple factual claim (sports records, historical facts, etc.)
SIMPLE_FACT_PATTERNS = [
    r'\b(?:won|win|winner|champion|championship|title|record|holder|captain|president|founder|inventor|discovered|created|wrote|directed|starred|played)\b',
    r'\b(?:born|died|established|founded|opened|launched|released|published)\s+(?:in|on)\s+\d',
    r'\b(?:is|was|are|were)\s+(?:the|a|an)\s+(?:\w+\s+){0,3}(?:champion|winner|holder|founder|president|prime\s+minister|king|queen|author|director|actor|actress|player|captain|coach|manager|inventor|scientist|artist|musician)\b',
    r'\b\d+\s*(?:time|times|x)\s+(?:world\s+)?champion\b',
    r'\b(?:world|national|olympic|grand\s+slam|world\s+cup)\s+(?:champion|record|title|winner|medal)\b',
]
_compiled_simple_fact = [re.compile(p, re.IGNORECASE) for p in SIMPLE_FACT_PATTERNS]


def _classify_claim_type(text):
    """
    Classify the type of claim being made.

    Returns:
        'news_study' — text references a study, report, or research (needs entity verification)
        'simple_fact' — text makes a factual claim about a person, record, event
        'general' — anything else
    """
    news_study_matches = sum(1 for p in _compiled_news_study if p.search(text))
    simple_fact_matches = sum(1 for p in _compiled_simple_fact if p.search(text))

    if news_study_matches >= 2:
        return 'news_study'
    elif news_study_matches >= 1 and simple_fact_matches == 0:
        return 'news_study'
    elif simple_fact_matches >= 1:
        return 'simple_fact'
    else:
        return 'general'


def _contains_ai_markers(text_lower):
    """Check if text contains AI-generated content markers."""
    return any(marker in text_lower for marker in AI_CONTENT_MARKERS)


def _is_extraordinary_claim(text):
    """Check if the claim matches known extraordinary/impossible patterns."""
    return any(p.search(text) for p in _compiled_extraordinary)


def _count_fantasy_indicators(text_lower):
    """Count how many fantasy/fabrication indicator phrases are present."""
    return sum(1 for phrase in FANTASY_INDICATORS if phrase in text_lower)


def _source_confirms_claim(snippet, query_words, claim_type='general'):
    """
    Check if a source actually CONFIRMS the claim vs just mentioning related topics.
    A source confirms only if it:
    1. Has sufficient keyword overlap
    2. Does NOT contain refutation keywords

    For simple_fact claims, we use a lower overlap threshold (0.20)
    because users might phrase facts informally.
    """
    snippet_lower = snippet.lower() if snippet else ''

    # Check for refutation in this source
    has_refutation = any(kw in snippet_lower for kw in REFUTATION_KEYWORDS)
    if has_refutation:
        return False

    # Check keyword overlap
    if not query_words:
        return False
    matched = sum(1 for w in query_words if w in snippet_lower)
    overlap = matched / len(query_words)

    # Use lower threshold for simple factual claims
    if claim_type == 'simple_fact':
        return overlap >= 0.20
    return overlap >= 0.30


def _build_search_query(text, claim_type):
    """
    Build a smarter search query based on claim type.

    For simple facts, extract the key subject and predicate.
    For news/study claims, include the institution/journal name.
    """
    clean_text = re.sub(r'breaking:?|viral social media|whatsapp forward', '', text, flags=re.IGNORECASE).strip()

    if claim_type == 'simple_fact':
        # For simple facts, use the raw text but trim it and add context
        query = clean_text[:150].strip()
        # Don't append "fact check" for simple facts — it biases toward debunking
        return query

    elif claim_type == 'news_study':
        query = clean_text[:120].strip()
        return f"{query} fact check"

    else:
        query = clean_text[:120].strip()
        return f"{query} fact check"


def _contains_fictional_qualifier(text_lower):
    """
    Check if the text explicitly uses words like 'fictional', 'fictitious',
    'hypothetical' near entity names — a dead giveaway of AI-generated
    fake news.
    """
    fictional_patterns = [
        r'\b(?:fictional|fictitious|hypothetical|imaginary|made[- ]?up|synthetic|not\s+real|simulated|fabricated|fake)\s+(?:[A-Z][a-zA-Z]+\s*){1,5}',
        r'\b(?:the\s+)?fictional\b',
    ]
    for p in fictional_patterns:
        if re.search(p, text_lower, re.IGNORECASE):
            return True
    return False


def search_and_verify(text):
    """
    Search the web for the claim and return a fact-check analysis.
    Uses duckduckgo-search (ddgs).

    IMPORTANT: This function is deliberately conservative about marking
    claims as "verified". It is much safer to return "unverified" than
    to falsely verify a fabricated claim.
    """
    # Extract a short query from the text (first sentence or up to 120 chars)
    # Apply robust text normalization first
    text = normalize_text(text)
    clean_text = re.sub(r'breaking:?|viral social media|whatsapp forward', '', text, flags=re.IGNORECASE).strip()

    if not clean_text or len(clean_text) < 10:
        return {'status': 'error', 'message': 'Query too short'}

    text_lower = normalize_for_heuristics(text)

    # --- Pre-flight checks: block verification for obviously problematic content ---

    # 1. AI-generated content should never be verified
    if _contains_ai_markers(text_lower):
        return {
            'status': 'debunked',
            'message': 'Content contains AI-generated text markers.',
            'sources': []
        }

    # 2. Check for "fictional" qualifier — dead giveaway of AI-generated content
    if _contains_fictional_qualifier(text_lower):
        return {
            'status': 'debunked',
            'message': 'Content references fictional/hypothetical entities — likely AI-generated.',
            'sources': [],
            'ai_fabrication_detected': True,
        }

    # 3. Classify the claim type for smarter verification
    claim_type = _classify_claim_type(text)

    # 4. Extraordinary claims need extraordinary evidence — flag them early
    is_extraordinary = _is_extraordinary_claim(text)
    fantasy_count = _count_fantasy_indicators(text_lower)

    # Build a smarter query based on claim type
    query = _build_search_query(text, claim_type)

    if not query:
        return {'status': 'error', 'message': 'Query too short'}

    if DDGS is None:
        return {'status': 'error', 'message': 'Web search library not available'}

    try:
        with DDGS() as ddgs:
            results = list(ddgs.text(query, max_results=5))

        if not results:
            # For simple facts, try a second search without "fact check"
            if claim_type != 'simple_fact':
                return {'status': 'unverified', 'message': 'No relevant fact-check results found.'}
            # Already searched without "fact check" for simple facts, truly no results
            return {'status': 'unverified', 'message': 'No relevant results found for this factual claim.'}

        debunk_score = 0
        confirm_score = 0
        total_results = len(results)
        sources_used = []
        refutation_found = False

        # Extract meaningful words from query for relevance checking
        query_words = set(re.findall(r'\b[a-zA-Z]{3,}\b', query.lower()))
        # Remove very common words that don't help with relevance
        common_words = {'the', 'and', 'for', 'are', 'was', 'were', 'has', 'had',
                        'have', 'been', 'not', 'but', 'with', 'this', 'that',
                        'from', 'who', 'what', 'when', 'where', 'how', 'why',
                        'will', 'can', 'all', 'one', 'two', 'time', 'fact', 'check'}
        query_words -= common_words

        for r in results:
            title = r.get('title', '').lower()
            snippet = r.get('body', '').lower()
            url = r.get('href', '')

            combined_text = title + " " + snippet + " " + url
            sources_used.append({'title': r.get('title'), 'url': url, 'snippet': snippet})

            # If a trusted fact checking site explicitly calls it false
            is_trusted = any(domain in url for domain in TRUSTED_DOMAINS)

            has_debunk = any(keyword in combined_text for keyword in DEBUNK_KEYWORDS)
            has_refutation = any(keyword in combined_text for keyword in REFUTATION_KEYWORDS)

            if has_debunk:
                if is_trusted:
                    debunk_score += 2  # Trusted sources carry more weight
                else:
                    debunk_score += 1

            if has_refutation:
                refutation_found = True
                debunk_score += 1

            # Check if this source actually confirms the claim
            if _source_confirms_claim(snippet, query_words, claim_type):
                if is_trusted:
                    confirm_score += 2  # Trusted confirmations count double
                else:
                    confirm_score += 1

        # --- Decision logic ---

        # DEBUNKED: Strong debunk evidence
        if debunk_score >= 2:
            return {
                'status': 'debunked',
                'message': 'Live Web Search: Claim has been debunked by fact-checkers.',
                'sources': sources_used[:3]
            }

        # NEVER verify extraordinary claims unless overwhelmingly confirmed
        if is_extraordinary or fantasy_count >= 2:
            # Even if we found some matching results, extraordinary claims
            # need extraordinary evidence. Require 3+ confirming trusted sources
            # with zero refutation.
            if confirm_score >= 3 and not refutation_found and debunk_score == 0:
                return {
                    'status': 'verified',
                    'message': 'Live Web Search: Extraordinary claim confirmed by multiple credible sources.',
                    'sources': sources_used[:3]
                }
            # Otherwise, stay unverified for extraordinary claims
            return {
                'status': 'unverified',
                'message': 'Live Web Search: Claim is extraordinary and could not be conclusively verified.',
                'sources': sources_used[:3]
            }

        # SIMPLE FACT VERIFICATION — more lenient for straightforward factual claims
        # like "X won Y championship" or "Z was born in 1969"
        if claim_type == 'simple_fact':
            if debunk_score == 0 and not refutation_found and confirm_score >= 1:
                return {
                    'status': 'verified',
                    'message': 'Live Web Search: Factual claim is supported by credible sources.',
                    'sources': sources_used[:3]
                }

        # NEWS/STUDY claims — be stricter (the institution/study might be fabricated)
        if claim_type == 'news_study':
            # For news/study claims, require stronger confirmation
            if debunk_score == 0 and not refutation_found and confirm_score >= 2:
                return {
                    'status': 'verified',
                    'message': 'Live Web Search: News claim is supported by credible sources.',
                    'sources': sources_used[:3]
                }
            # If no clear confirmation, lean toward unverified
            return {
                'status': 'unverified',
                'message': 'Live Web Search: Could not conclusively verify this news/study claim.',
                'sources': sources_used[:3]
            }

        # VERIFIED: Only for normal claims with strong evidence
        # Requirements:
        # 1. Zero debunk signals
        # 2. At least 1 trusted source that actually confirms (not just mentions)
        # 3. No refutation found anywhere
        if debunk_score == 0 and not refutation_found and total_results >= 1:
            if confirm_score >= 1:
                return {
                    'status': 'verified',
                    'message': 'Live Web Search: Claim is supported by credible sources.',
                    'sources': sources_used[:3]
                }

        return {
            'status': 'unverified',
            'message': 'Live Web Search: Results found, but inconclusive.',
            'sources': sources_used[:3]
        }

    except Exception as e:
        print(f"Web Search Error: {e}")
        return {'status': 'error', 'message': f'Search failed: {str(e)}'}
