"""
Comprehensive test suite for verifying the AI judgment fixes.
Tests that GPT/fantasy statements, false geo-political claims, and
fabricated financial data are correctly classified as FAKE.
Also tests that legitimate news is NOT falsely flagged as FAKE.
"""

import sys
import os

# Add project root to path
sys.path.insert(0, os.path.abspath(os.path.dirname(__file__)))

from app import create_app, db
from app.services.classifier import predict, load_model, _heuristic_predict
from app.services.fact_checker import (
    _contains_ai_markers, _is_extraordinary_claim,
    _count_fantasy_indicators
)


def test_classifier_only():
    """Test the heuristic classifier WITHOUT fact checking."""
    print("\n" + "=" * 70)
    print("PART 1: HEURISTIC CLASSIFIER TESTS (no web search)")
    print("=" * 70)

    # --- MUST BE CLASSIFIED AS FAKE ---
    fake_cases = [
        (
            "As an AI language model, I can confirm that the government is hiding evidence of alien technology",
            "AI language model marker"
        ),
        (
            "This article was generated by GPT to test the system. The president has declared martial law.",
            "GPT generation marker"
        ),
        (
            "GPT-5 has been secretly deployed by the CIA to control social media in 190 countries",
            "Fantasy: CIA secretly deployed AI"
        ),
        (
            "Elon Musk announced he is giving away $1 million to every Twitter user starting tomorrow",
            "Fantasy: Elon giving away money to every user"
        ),
        (
            "NASA confirmed aliens landed in New Delhi on July 14, 2026",
            "Fantasy: Aliens landed"
        ),
        (
            "Bitcoin reached $5 million per coin today after a stunning rally that stunned the world",
            "Absurd financial: Bitcoin $5 million"
        ),
        (
            "Apple's stock price crashed to $0.50 per share in early morning trading",
            "Absurd financial: Stock crash to $0.50"
        ),
        (
            "The US national debt was paid off completely in June 2026",
            "Absurd financial: National debt paid off"
        ),
        (
            "India's GDP grew 25% in Q2 2026, according to leaked government documents",
            "Absurd political: GDP grew 25%"
        ),
        (
            "Vladimir Putin resigned as President of Russia in a shocking move that stunned the world",
            "Absurd political: Putin resigned"
        ),
        (
            "The United States declared war on Canada after a border dispute escalated",
            "Absurd political: US declared war on Canada"
        ),
        (
            "Scientists confirm that drinking bleach cures all diseases, doctors hate this one weird trick. Drank bleach and feel great!",
            "Troll content with clickbait"
        ),
        (
            "Big pharma is hiding the miracle cure for cancer! Vaccines cause autism and the government is covering it up!",
            "Health misinformation"
        ),
        (
            "BREAKING: World leaders are panicking as anonymous sources confirm a global financial collapse is imminent. Share before it's too late!",
            "Viral hoax pattern"
        ),
    ]

    # --- MUST NOT BE CLASSIFIED AS FAKE ---
    real_cases = [
        (
            "Reuters: India's central bank held interest rates steady at 6.5% on Thursday, in line with market expectations, as inflation eased to 4.87% in April. The Reserve Bank of India said in a statement that the decision was unanimous among the six-member monetary policy committee.",
            "Legitimate Reuters-style financial news"
        ),
        (
            "BBC News: The United Nations Security Council held an emergency session on climate change on Monday, according to a spokesperson. The session focused on rising sea levels and their impact on island nations. Representatives from 15 member states reportedly participated in the discussion.",
            "Legitimate BBC-style political news"
        ),
        (
            "Apple Inc. reported quarterly earnings of $1.52 per share, beating analyst estimates of $1.43. Revenue rose 5% year-over-year to $94.8 billion, the company said in a press release. CEO Tim Cook told reporters that services revenue was a key growth driver.",
            "Legitimate earnings report"
        ),
        (
            "According to the World Health Organization, the global COVID-19 vaccination rate has reached 73% as of June 2026. The WHO spokesperson confirmed that new booster programs are being rolled out in several countries, reportedly targeting vulnerable populations.",
            "Legitimate WHO health news"
        ),
    ]

    print("\n--- FAKE DETECTION TESTS (should all be FAKE) ---\n")
    fake_pass = 0
    fake_fail = 0
    for text, desc in fake_cases:
        result = _heuristic_predict(text)
        label = result['label']
        confidence = result['confidence']
        fake_prob = result['fake_prob']
        status = "[PASS]" if label == 'FAKE' else "[FAIL]"
        if label == 'FAKE':
            fake_pass += 1
        else:
            fake_fail += 1
        features = result.get('features', [])[:3]
        print(f"  {status} | {desc}")
        print(f"         Label={label}, fake_prob={fake_prob:.2f}, confidence={confidence:.2f}")
        if features:
            print(f"         Triggers: {'; '.join(features[:2])}")
        print()

    print("\n--- REAL DETECTION TESTS (should all be REAL) ---\n")
    real_pass = 0
    real_fail = 0
    for text, desc in real_cases:
        result = _heuristic_predict(text)
        label = result['label']
        confidence = result['confidence']
        fake_prob = result['fake_prob']
        status = "[PASS]" if label == 'REAL' else "[FAIL]"
        if label == 'REAL':
            real_pass += 1
        else:
            real_fail += 1
        features = result.get('features', [])[:3]
        print(f"  {status} | {desc}")
        print(f"         Label={label}, fake_prob={fake_prob:.2f}, confidence={confidence:.2f}")
        if features:
            print(f"         Triggers: {'; '.join(features[:2])}")
        print()

    print(f"\n--- CLASSIFIER SUMMARY ---")
    print(f"  Fake tests: {fake_pass}/{len(fake_cases)} passed")
    print(f"  Real tests: {real_pass}/{len(real_cases)} passed")
    print(f"  Total: {fake_pass + real_pass}/{len(fake_cases) + len(real_cases)} passed")

    return fake_fail == 0 and real_fail == 0


def test_fact_checker_preflight():
    """Test the fact checker's pre-flight checks (no web search needed)."""
    print("\n" + "=" * 70)
    print("PART 2: FACT CHECKER PRE-FLIGHT TESTS (no web search)")
    print("=" * 70)

    ai_tests = [
        ("As an AI language model, I can confirm this is true", True),
        ("Generated by GPT for testing purposes", True),
        ("This is a normal news article about technology", False),
    ]

    print("\n--- AI Marker Detection ---")
    all_pass = True
    for text, expected in ai_tests:
        result = _contains_ai_markers(text.lower())
        status = "[PASS]" if result == expected else "[FAIL]"
        if result != expected:
            all_pass = False
        print(f"  {status} | AI={result} (expected={expected}) | {text[:60]}...")

    extraordinary_tests = [
        ("Bitcoin reached $5 million per coin today", True),
        ("GDP grew 25% in Q2 2026", True),
        ("Putin resigned as President of Russia", True),
        ("US declared war on Canada", True),
        ("Aliens landed in New Delhi", True),
        ("CIA secretly deployed the system", True),
        ("India's central bank held rates at 6.5%", False),
        ("Apple reported earnings of $1.52 per share", False),
    ]

    print("\n--- Extraordinary Claim Detection ---")
    for text, expected in extraordinary_tests:
        result = _is_extraordinary_claim(text)
        status = "[PASS]" if result == expected else "[FAIL]"
        if result != expected:
            all_pass = False
        print(f"  {status} | Extraordinary={result} (expected={expected}) | {text[:60]}...")

    fantasy_tests = [
        ("Has been secretly deployed in 190 countries, sending shockwaves", 3),
        ("Normal news article about the economy", 0),
    ]

    print("\n--- Fantasy Indicator Counting ---")
    for text, min_expected in fantasy_tests:
        result = _count_fantasy_indicators(text.lower())
        passed = result >= min_expected if min_expected > 0 else result == 0
        status = "[PASS]" if passed else "[FAIL]"
        if not passed:
            all_pass = False
        print(f"  {status} | Count={result} (expected>={min_expected}) | {text[:60]}...")

    return all_pass


def test_ssrf_protection():
    """Test SSRF protection in rss_fetcher."""
    print("\n" + "=" * 70)
    print("PART 3: SSRF PROTECTION TESTS")
    print("=" * 70)

    from app.services.rss_fetcher import fetch_article_content

    ssrf_urls = [
        "http://127.0.0.1:8080/admin",
        "http://localhost/secret",
        "http://192.168.1.1/router",
        "http://10.0.0.1/internal",
    ]

    all_pass = True
    for url in ssrf_urls:
        result = fetch_article_content(url)
        blocked = result.get('error') is not None and result.get('text', '') == ''
        status = "[PASS]" if blocked else "[FAIL]"
        if not blocked:
            all_pass = False
        print(f"  {status} | Blocked={blocked} | {url}")

    return all_pass


def test_input_sanitization():
    """Test input sanitization."""
    print("\n" + "=" * 70)
    print("PART 4: INPUT SANITIZATION TESTS")
    print("=" * 70)

    import re as _re
    def _strip_html(s):
        return _re.sub(r'<[^>]+>', '', s) if s else ''

    tests = [
        ('<script>alert("xss")</script>Normal text', 'alert("xss")Normal text'),
        ('<b>Bold</b> and <i>italic</i>', 'Bold and italic'),
        ('No HTML here', 'No HTML here'),
    ]

    all_pass = True
    for input_text, expected in tests:
        result = _strip_html(input_text)
        passed = result == expected
        status = "[PASS]" if passed else "[FAIL]"
        if not passed:
            all_pass = False
        print(f"  {status} | Input: {input_text[:40]}...")
        print(f"         Output: {result[:40]}...")

    return all_pass


if __name__ == '__main__':
    app = create_app('testing')
    with app.app_context():
        load_model()

        results = []
        results.append(("Classifier Tests", test_classifier_only()))
        results.append(("Fact Checker Pre-flight", test_fact_checker_preflight()))
        results.append(("SSRF Protection", test_ssrf_protection()))
        results.append(("Input Sanitization", test_input_sanitization()))

        print("\n" + "=" * 70)
        print("FINAL RESULTS")
        print("=" * 70)
        all_pass = True
        for name, passed in results:
            status = "[PASS]" if passed else "[FAIL]"
            if not passed:
                all_pass = False
            print(f"  {status} | {name}")

        print()
        if all_pass:
            print("ALL TESTS PASSED!")
        else:
            print("SOME TESTS FAILED - review output above")

        sys.exit(0 if all_pass else 1)
